# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20171201_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='realtime',
            new_name='sign',
        ),
    ]
